Issue #173 services need status target (#718)
* add status subcommand to geserver and gefusion service scripts (#173)
* fixed installer copy-paste error (#173)
* Minor changes of capitalization of user message and format of code (#173)
* Quote uses of variables, indent more consistently, print pid of each running process, simplify code (#173)
* replace ps-and-grep method to check for running daemon with more precise checks of /proc; further simplify code.

diff --git a/earth_enterprise/src/fusion/autoingest/sysman/gefusion b/earth_enterprise/src/fusion/autoingest/sysman/gefusion
--- a/earth_enterprise/src/fusion/autoingest/sysman/gefusion
+++ b/earth_enterprise/src/fusion/autoingest/sysman/gefusion
@@ -58,17 +58,34 @@ function check_if_master {
 }
 
 function stop_daemon {
-    echo -n "Shutting down $2... "
-    pidfile="/var/opt/google/run/$1.pid"
-    if [ -e $pidfile ] ; then
-	if gestopdaemon $1 ; then
-	    echo "Done"
-	else
-	    echo "Failed"
-	fi
+  echo -n "Shutting down $2... "
+  pidfile="/var/opt/google/run/$1.pid"
+  if [ -e "$pidfile" ] ; then
+    if gestopdaemon $1 ; then
+      echo "Done"
     else
-	echo "Not running"
+      echo "Failed"
     fi
+  else
+    echo "Not running"
+  fi
+}
+
+function check_daemon {
+  # more DRY to use "gefdaemoncheck --checkrunning"
+  #   but it seems to assume --checksysman is true
+  #   thus wont work on non-master hosts.
+  daemon_path=$(which "$1")
+  pidfile="/var/opt/google/run/$1.pid"
+  if [ -s "$pidfile" ] ; then
+    pid=`cat "$pidfile"`
+    if [ -d "/proc/$pid" ] && [ "$(readlink "/proc/$pid/exe")" = "$daemon_path" ]; then
+      echo "$1:  Running (PID $pid)."
+      return 0
+    fi
+  fi
+  echo "$1:  Not running."
+  return 1
 }
 
 start() {
@@ -105,23 +122,35 @@ stop() {
   fi
 }
 
+status() {
+  return_code=0
+  if check_if_master ; then
+    check_daemon gesystemmanager || return_code=1
+  fi
+  check_daemon geresourceprovider || return_code=1
+  return "$return_code"
+}
+
 case "$1" in
     restart)
-    stop
-    sleep 1
-    start
-    ;;
+      stop
+      sleep 1
+      start
+      ;;
     start)
-    start
-    ;;
+      start
+      ;;
     stop)
-    stop
-    ;;
+      stop
+      ;;
+    status)
+      status
+      exit $?
+      ;;
     *)
-    echo "usage: $0 {start|stop|restart}"
-    exit 1
-    ;;
-
+      echo "usage: $0 {start|stop|restart|status}"
+      exit 1
+      ;;
 esac
 
 exit 0
